WHITE_KING = "\u2654"
WHITE_QUEEN = "\u2655"
WHITE_ROOK = "\u2656"
WHITE_BISHOP = "\u2657"
WHITE_KNIGHT = "\u2658"
WHITE_PAWN = "\u2659"

BLACK_KING = "\u265A"
BLACK_QUEEN = "\u265B"
BLACK_ROOK = "\u265C"
BLACK_BISHOP = "\u265D"
BLACK_KNIGHT = "\u265E"
BLACK_PAWN = "\u265F"

WHITE_PIECES = [WHITE_KING, WHITE_QUEEN, WHITE_ROOK, WHITE_BISHOP, WHITE_KNIGHT, WHITE_PAWN]
BLACK_PIECES = [BLACK_KING, BLACK_QUEEN, BLACK_ROOK, BLACK_BISHOP, BLACK_KNIGHT, BLACK_PAWN]

KING = [WHITE_KING, BLACK_KING]
QUEEN = [WHITE_QUEEN, BLACK_QUEEN]
ROOK = [WHITE_ROOK, BLACK_ROOK]
BISHOP = [WHITE_BISHOP, BLACK_BISHOP]
KNIGHT = [WHITE_KNIGHT, BLACK_KNIGHT]
PAWN = [WHITE_PAWN, BLACK_PAWN]
